### PR TITLE
Re-generate cpp files using thrift 0.17

### PR DESCRIPTION
**Pull request by DomGarguilo**
These changes are automatically generated.

### CODE REVIEW

**Comment by DomGarguilo** [comment]
I am marking this as draft for now so it is not merged yet. For some reason two of the files were not regenerated with thrift 0.17.0 and remain at 0.12.0. Those files are `proxy_constants.cpp` and `proxy_constants.h`. I'm not sure if they didn't need to be regenerated or somehow were included inside of one or more of the other files but this should probably be figured out before this is merged.

**Comment by DomGarguilo** [comment]
Also, I did not test these changes since there is no given test client file available here like there is for python and ruby.

**Comment by DomGarguilo** [comment]
Superseded by 7bcf98a44cdec584b69b2f0e8c809b3b931518a3

**Comment by ctubbsii** [comment]
@DomGarguilo I didn't realize you already had some PRs open for some of these when I made my recent updates. Sorry for stepping on your toes for these.

**Pull request closed without merging**
