### PR TITLE
Fix #3 Updated the accumulo-proxy with latest from accumulo (pre-2.0)

### LINKED ISSUE #3: Relocate accumulo-proxy to separate repository on its own release schedule
accumulo-proxy is really a separate project from the core Accumulo distribution, and I think it should be shipped separately, and maintained separately in its own repo.

This will also help isolate the maintenance interest, so that if there isn't any current interest, no time is wasted on it, and if there is, work can be done independently from the releases of the core Accumulo distribution.

### PR DESCRIPTION
**Pull request by hkeebler**
This builds and verifies with the updates from the accumulo project.  The IT tests were moved over and execute.  Not sure if more testing needs to be done.  
 The couple of quirky things are:
Added the Encoding exculsion to ProxyDurabilityIT test.  This was not necessary in the accumulo project and I'm not sure how it was excluded there.
  ```
@SuppressFBWarnings(value = {"HARD_CODE_PASSWORD", "DM_DEFAULT_ENCODING"},
      justification = "test password is okay and no check needed on encoding")
```
Added the Throwable in ProxyServer because it did not pass some code check.
```
catch (Throwable e) {
      handleException(new Exception(e));
```

### CODE REVIEW

**Comment by ivakegg** [comment]
> Added the Throwable in ProxyServer because it did not pass some code check.
> 
> ```
> catch (Throwable e) {
>       handleException(new Exception(e));
> ```

Catching Throwable is a very dangerous thing to do.  We need to fix the verify to allow catching exception here instead.

**Comment by ivakegg** [comment]
Looking at the generate-thrift script, there are some changes that are suspect.  Comparing to the commit just before proxy was removed from the accumulo base:
diff accumulo/core/src/main/scripts/generate-thrift.sh accumulo-proxy/src/main/scripts/generate-thrift.sh 

I saw the following:
<   thrift ${THRIFT_ARGS} --gen java:generated_annotations=suppress "$f" || fail unable to generate java thrift classes
---
>   thrift ${THRIFT_ARGS} --gen java:generated_annotations=undated,handle_runtime_exceptions "$f" || fail unable to generate java thrift classes

**Comment by hkeebler** [comment]
@ivakegg updated the throwable with the spotbugs recommended solution below.  It now also passes the verify.
} catch (RuntimeException e) {
      throw (e);
    } catch (Exception e) {
      handleException(e);
      return null;

**Comment by hkeebler** [comment]
Clicked the wrong button again.  My apologies.  This is still an open pull request.  The thrift build was verified and this last commit will include the generated_annotations=suppressed argument in the generate_thrift.sh.

**Comment by ctubbsii** [comment]
Totally lost track of this PR. Merged today. Doesn't look like all the ITs are passing, but can be fixed in follow-on.

**Pull request merged**
