### PR TITLE
Update logging

### PR DESCRIPTION
**Pull request by DomGarguilo**
This PR updates the logging in this repo.

Things seem to work correctly for the most part although for some reason, only the `log.error` statements are being printed during the tests. This might be caused by some config issue but I am not sure. 

I based these changes off of some of the other repositories dependencies but I am not sure that everything is correct or optimal.

### CODE REVIEW

**Comment by dlmarion** [comment]
We removed SLF4J?

**Comment by DomGarguilo** [comment]
> We removed SLF4J?

Oops, maybe not. I'll add it back.

**Comment by DomGarguilo** [comment]
> We removed SLF4J?

So actually the slf4j dependencies where removed from the pom because the `log4j-slf4j2-impl` provides an slf4j "provider". If the `org.slf4j` dependencies are present, a warning is thrown.

**Comment by EdColeman** [comment]
In the main accumulo pom - log4j-slf4j2-impl is declared as unused dependency.  For proxy, would runtime or provided scope be more appropriate and resolve the build error?  The real dependency is slf4j - the implementation(s) provided by log4j2 could also be satisfied with logback (I think, it has been I while since I have used that instead of log4j2) so is the -impl is transient and needs to be provided at runtime (and for tests?) but that is a runtime detail and not a dependency in maven build terms.

**Comment by ctubbsii** [comment]
Superseded by my fix to logging in 7bcf98a44cdec584b69b2f0e8c809b3b931518a3

**Pull request closed without merging**
